
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtljfgstevhzdkkaakmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0bGpmZ3N0ZXZoemRra2Fha21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NjcwMDksImV4cCI6MjA2MzI0MzAwOX0.hZEMnt4-IKCEjQPFA6hkuj_v_6jNpMqr2nRikFmdEDA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
